server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog/db.changelog.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui:
    path: /api
  api-docs:
    path: /v1/api-docs

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    root: DEBUG
    change-log: DEBUG

currency:
  usd: 1.0        # базовая валюта
  eur: 0.91       # 1 EUR ≈ 0.91 USD
  byn: 0.30       # 1 BYN ≈ 0.30 USD
  rub: 0.013      # 1 RUB ≈ 0.013 USD

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}
  expiration:
    access: ${JWT_EXPIRATION_ACCESS_TIME}
    refresh: ${JWT_EXPIRATION_REFRESH_TIME}